### ISSUE TITLE
自动命名中的时间连接符不符合文件命名规则

### ISSUE THREAD

**Issue by yoghurtdewdew** [wah0713/getWeiboImage#3]
下载时会自动命名，命名中带有时间，显示为字符“\”，粘贴出来发现是“/”，图片上传到百度云盘会被认为命名不合法无法上传，上传到夸克网盘被识别为“:”…… 
所以图片的自动命名中的时间连接符跟随文件夹改成“_”可能会更佳？防止后面整理文件时发生冲突
或者请教一下如何自己手动进行设置？没找到手动设置的地方，也看不懂脚本，所以上报这个问题
![image](https://user-images.githubusercontent.com/63794438/236627969-c5394dae-6af1-4982-881e-c0b335c9f728.png)
![image](https://user-images.githubusercontent.com/63794438/236628161-83c3674d-01f5-433e-883b-c546aa0f44f2.png)

**Comment by wah0713** [comment]
首先，感谢你的反馈。
这个问题是【:】在操作系统的是不能命名的。所以系统会替用户改名。
我打算个弄新的新的时间格式。【2023Y05M08D10H20m】

**Comment by wah0713** [comment]
首先，感谢你的反馈。
这个问题是【:】在操作系统的是不能命名的。所以系统会替用户改名。
我打算个弄新的新的时间格式。【2023Y05M08D10H20m】

**Comment by wah0713** [comment]
首先谢谢你的反馈，
已经按照你的说的来调整。
请手动更新至1.8.3版本
![image](https://user-images.githubusercontent.com/19662535/236841123-00fc2911-d703-4979-b51d-0fbe2fe64fc0.png)

**Comment by yoghurtdewdew** [comment]
已更新，但发现好像还是原来的命名规则：
![image](https://github.com/wah0713/getWeiboResources/assets/63794438/79437813-c128-4635-9ebb-72a2e1dd7260)
![image](https://github.com/wah0713/getWeiboResources/assets/63794438/c2c27f0f-c55d-4fde-a5eb-6de94511fea9)
客户端：macos M1 13.1 (22C65)，Edge 111.0.1661.62 (正式版本) (arm64)，油猴

**Comment by wah0713** [comment]
> 已更新，但发现好像还是原来的命名规则： ![image](https://user-images.githubusercontent.com/63794438/238122600-79437813-c128-4635-9ebb-72a2e1dd7260.png) ![image](https://user-images.githubusercontent.com/63794438/238122604-c2c27f0f-c55d-4fde-a5eb-6de94511fea9.png) 客户端：macos M1 13.1 (22C65)，Edge 111.0.1661.62 (正式版本) (arm64)，油猴

你有没把上图的开关开启?默认是关闭

**Comment by wah0713** [comment]
我用去试了一遍没有问题。
你有没有把这个开关开启。默认是关闭

**Comment by wah0713** [comment]
> 首先谢谢你的反馈， 已经按照你的说的来调整。 请手动更新至1.8.3版本 ![image](https://user-images.githubusercontent.com/19662535/236841123-00fc2911-d703-4979-b51d-0fbe2fe64fc0.png)

我刚才试了下功能，正确运行。
你检查有没有把这个功能开启(默认是关闭)

**Comment by yoghurtdewdew** [comment]
感谢指导！我检查了下，确实是忘了手动打开这个选项
