### ISSUE TITLE
点击下载，下载的是m3u8文件，并没有直接把视频下载下来

### ISSUE THREAD

**Issue by sunddytwo** [wah0713/getWeiboImage#4]
点击下载，下载的是m3u8文件，并没有直接把视频下载下来

**Comment by sunddytwo** [comment]
测试地址：https://video.weibo.com/show?fid=1042211:4903603312459904

**Comment by wah0713** [comment]
首先谢谢你的反馈。
m3u8文件都要额外解析。
我打算屏蔽这类链接吧。
能力有限见谅。

**Comment by wah0713** [comment]
![image](https://github.com/wah0713/getWeiboResources/assets/19662535/69dc3900-4aad-4127-9d2b-eb78d64bdcbc)
我居然做出来了，我打算周末推出1.9.0支持m3u8类视频，尽请期待。现在还差一个任务队列。

**Comment by wah0713** [comment]
好了，手动下载1.9.0版本试试效果
