### ISSUE TITLE
压缩包里的文件名能否支持自定义字段的先后顺序？

### ISSUE THREAD

**Issue by Hyton411** [wah0713/getWeiboImage#5]
比如文件名先是时间后是ID，或者自定义其他顺序呢？

**Comment by wah0713** [comment]
首先谢谢你的反馈。
其实我一直在想怎么做一个大家都觉得【简单】的文件名自定义顺序。
一直没有想到比较好的交互。
最近工作上给了我灵感。
so 就有这个2.0.0版本，已经支持了。
请手动更新2.0.0版本。谢谢支持。
![2.0.0](https://s1.ax1x.com/2023/06/08/pCAetiR.png)
