### ISSUE TITLE
下载视频的前提下，一条微博下面只有一个视频才是最清晰的那一档，如果一条微博是多个视频下载的是最低清晰度的

### ISSUE THREAD

**Issue by JYWXJ327** [wah0713/getWeiboImage#8]

**Comment by JYWXJ327** [comment]
还有一个问题，已经编辑过的图片微博，进入微博编辑记录有下载的选项但是点击无反应

**Comment by wah0713** [comment]
第一个多视频的，可以的话麻烦说下哪里有高清的视频资源。确实没有找到。

**Comment by wah0713** [comment]
> 还有一个问题，已经编辑过的图片微博，进入微博编辑记录有下载的选项但是点击无反应

麻烦给个链接，让我看看什么情况，我发现个事编辑微博内容居然要会员。

**Comment by JYWXJ327** [comment]
> 第一个多视频的，可以的话麻烦说下哪里有高清的视频资源。确实没有找到。

这个是“https://weibo.com/7861642902/NflVvxQPG”两个视频的，下载完是以下大小
![WVS34{$(@JNQR 6Q94NLKOB](https://github.com/wah0713/getWeiboResources/assets/112244957/6ce3b47c-7be0-413a-9bf9-ee7c5284ab6f)
单独拿出来解析出来是以下大小
![T~HK1JRIJVGTR~%NPY{6SJP](https://github.com/wah0713/getWeiboResources/assets/112244957/d8210d3c-fe9d-47d9-9fe8-a09be6bb4497)

![HG73XFO6~ `50K%7LP@TBQV](https://github.com/wah0713/getWeiboResources/assets/112244957/1477c4a7-f8be-4ca6-9313-99f4d501de59)

**Comment by JYWXJ327** [comment]
> > 还有一个问题,已经编辑过的图片微博,进入微博编辑记录有下载的选项但是点击无反应
> 
> 麻烦给个链接,让我看看什么情况,我发现个事编辑微博内容居然要会员。

“https://weibo.com/7861642902/NgyeV3V6P”比如这条已经编辑过的微博，查看编辑记录之后，有“下载”这个按钮但是是没有反应的

**Comment by wah0713** [comment]
请手动更新到2.2.0版本。
右上角选择【是否下载最高清的视频】
https://wah0713.github.io/getWeiboResources/readme.md

**Comment by JYWXJ327** [comment]
> 请手动更新到2.2.0版本。 右上角选择【是否下载最高清的视频】 https://wah0713.github.io/getWeiboResources/readme.md

另一个问题可以处理嘛 
如果可以解决，还有一个问题已经编辑过的图片下载下来是否可以判断为重复文件，例如下面这个显示只编辑了一张
https://weibo.com/7861642902/NdQ4MyYqk
![image](https://github.com/wah0713/getWeiboResources/assets/112244957/bff2563d-3ec4-4702-82e1-1aaa0a3fcba1)

**Comment by wah0713** [comment]
> > 请手动更新到2.2.0版本。 右上角选择【是否下载最高清的视频】 https://wah0713.github.io/getWeiboResources/readme.md
> 
> 另一个问题可以处理嘛 如果可以解决，还有一个问题已经编辑过的图片下载下来是否可以判断为重复文件，例如下面这个显示只编辑了一张 https://weibo.com/7861642902/NdQ4MyYqk ![image](https://user-images.githubusercontent.com/112244957/266091868-bff2563d-3ec4-4702-82e1-1aaa0a3fcba1.png)

这个不好做，不做了。🤣
